# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [5]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =", a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =", a.shape,"\nразмер матрицы b =", b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.96567823 0.98609595 0.3082798  ... 0.61641517 0.22361298 0.67067215]
 [0.15394749 0.6261437  0.44591553 ... 0.36098989 0.43657902 0.88488758]
 [0.14722354 0.60902124 0.49127133 ... 0.17894689 0.78055711 0.92981532]
 ...
 [0.06607363 0.27998303 0.89715616 ... 0.65847871 0.86287529 0.35606859]
 [0.82160693 0.38852472 0.90623826 ... 0.82900072 0.84346476 0.73679637]
 [0.72265316 0.86694299 0.78372061 ... 0.59988949 0.69038933 0.53253836]]
[[0.85917067 0.44763127 0.75980012 ... 0.67724981 0.0165184  0.13466246]
 [0.15764261 0.02099022 0.54151656 ... 0.08896454 0.09750181 0.17993442]
 [0.62699757 0.85638084 0.88181084 ... 0.81152837 0.51055525 0.80634259]
 ...
 [0.15261356 0.58262437 0.73584523 ... 0.24063906 0.62289834 0.26795704]
 [0.51585162 0.59768435 0.71102113 ... 0.85818919 0.72852473 0.52653968]
 [0.31344728 0.45276108 0.1542171  ... 0.9211414  0.96276179 0.8243797 ]]
[[29.73617642665199, 29.3013

Без использования numpy

In [ ]:
def mult(a, b):
    result = [[sum(el1 * el2 for el1, el2 in zip (a_row, b_col)) for b_col in zip(* b)]for a_row in a]
    return result

C использованием numpy



In [ ]:
def np_mult(a, b):
    result = np.matmul(a, b)
    return result

In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 616 ms, sys: 1.27 ms, total: 617 ms
Wall time: 630 ms


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 341 µs, sys: 35 µs, total: 376 µs
Wall time: 230 µs


In [ ]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.4942713733034907e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)
# print(np_scalar_product(a,b))

[0.61643784 0.17905007 0.47998637] [0.45191701 0.20305419 0.55665106]
0.5821205258508129


In [ ]:
def scalar_product(a,b):
    s = sum([a[i]*b[i] for i in range(len(a))])
    return s

In [ ]:
def np_scalar_product(a,b):
    s = np.dot(a, b)
    return s

In [ ]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 984 µs, sys: 0 ns, total: 984 µs
Wall time: 994 µs
CPU times: user 22 µs, sys: 0 ns, total: 22 µs
Wall time: 25.3 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** ________________________________

------------------

### Задание 3
Напишите функцию, которая находит сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    diag_elem = np.diagonal(a)
    return diag_elem[diag_elem % 2 == 0].sum()

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
print(a, np_diag_2k(a))

[[3 9 3 6 3]
 [7 9 1 8 2]
 [5 1 7 8 9]
 [2 5 4 3 9]
 [6 7 3 8 5]] 0


In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 105 µs, sys: 0 ns, total: 105 µs
Wall time: 111 µs


0

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [7]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    A = np.array(A)
    summa = np.cumsum(A, axis=1)
    k = np.arange(1, A.shape[1] + 1).reshape(1, -1)
    result = summa / k
    return result

In [8]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
# print(A)

%time S2 = np_sec_av(A)

CPU times: user 170 µs, sys: 0 ns, total: 170 µs
Wall time: 178 µs


### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [11]:
def np_encode(X):
    result = [], []
    for key, group in groupby(X):
        result[0].append(key)
        result[1].append(len(list(group)))
    return np.array(result[0]), np.array(result[1])

In [12]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 52 µs, sys: 0 ns, total: 52 µs
Wall time: 56.5 µs


### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [13]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    result = np.copy(X)
    result[1::2] = a
    result[0::2] **= 3
    result = np.flip(result)
    result = np.concatenate((X, result))
    return result

In [14]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 171 µs, sys: 0 ns, total: 171 µs
Wall time: 177 µs
